# Generated by Django 4.2.7 on 2023-11-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='language_skills_level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Expert', 'Expert')], default='Basic', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='programming_skills_level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Expert', 'Expert')], default='Basic', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='language_skills',
            field=models.CharField(choices=[('Telugu', 'Telugu'), ('Tamil', 'Tamil'), ('English', 'English')], default='English', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='programming_skills',
            field=models.CharField(choices=[('Python', 'Python'), ('C#', 'C#'), ('PHP', 'PHP')], default=None, max_length=10, null=True),
        ),
    ]
