# Generated by Django 4.2.7 on 2023-11-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee_language_skills_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='doj',
            new_name='dob',
        ),
    ]
