# Generated by Django 4.2.7 on 2023-11-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_doj_employee_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='programming_skills_level',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='language_skills',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='programming_skills',
        ),
        migrations.AddField(
            model_name='employee',
            name='language_skills',
            field=models.ManyToManyField(blank=True, to='app.language'),
        ),
        migrations.AddField(
            model_name='employee',
            name='programming_skills',
            field=models.ManyToManyField(blank=True, to='app.programminglanguage'),
        ),
    ]
