# Generated by Django 4.2.7 on 2023-11-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_language_name_alter_programminglanguage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='programming_skills_level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Expert', 'Expert')], default='Basic', max_length=10, null=True),
        ),
    ]
