# Generated by Django 4.2.7 on 2023-11-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_employee_language_skills_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='programming_skills',
            field=models.ManyToManyField(to='app.programminglanguage'),
        ),
    ]
