# Generated by Django 4.2.7 on 2023-11-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_employee_programming_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('1', 'Telugu'), ('2', 'Tamil'), ('3', 'English')], max_length=50),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='name',
            field=models.CharField(choices=[('1', 'Python'), ('2', 'C#'), ('3', 'PHP')], max_length=50),
        ),
    ]
